name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Specify self-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh user@172.18.1.111 <<EOF
          cd /var/www/html/myproject
          git pull origin main
          sudo systemctl restart nginx
          EOF
