name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust this if your branch name is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 172.18.1.111  # Your server's IP
        username: sammy     # Your SSH user
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Reference to the private key secret
        port: 22            # Default SSH port, adjust if needed
        script: |
          cd /var/www/html/myproject
          git reset --hard  # Reset any uncommitted changes (optional but recommended)
          git pull origin main
          composer install --no-dev --optimize-autoloader  # Laravel projects (adjust as needed)
          php artisan migrate --force  # Apply migrations (if applicable)
          php artisan optimize         # Optimize the application
          sudo systemctl restart nginx # Restart web server or relevant service

